name: ecommerse
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  vector_math: ^2.1.2
  envify: ^2.0.2
  provider: ^6.0.3
  audioplayers: ^1.1.0
  intl: ^0.17.0
  carousel_slider: ^4.1.1
  equatable: ^2.0.5
  glassmorphism: ^3.0.0
  flutter_svg: ^1.1.6
  animations: ^2.0.7
  font_awesome_flutter: ^10.2.1
  image_sequence_animator: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/ticket/
    - assets/sytravel/
    - assets/drawer3d/
    - assets/pino/
    - assets/icons/
    - assets/garden/
    - assets/svg/
    - assets/evening/
    - assets/painting/
    - assets/vertical/
    - assets/transition/
    - assets/bottom_sheet/
    - assets/guitarsequence/

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Ultralight.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Display-Black.otf
          weight: 900
    - family: NothingYouCouldDo
      fonts:
        - asset: assets/fonts/NothingYouCouldDo.ttf    
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
